---
- name: Deploy VCF SDDC Manager from OVA
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Deploy VCF OVA
      ansible.builtin.shell: |
        /root/ovftool/ovftool \
          --acceptAllEulas \
          --noSSLVerify \
          --skipManifestCheck \
          --X:injectOvfEnv \
          --allowExtraConfig \
          --X:waitForIp \
          --sourceType=OVA \
          --powerOn \
          --net:"Network 1"="VM Network" \
          --datastore="nvme2" \
          --diskMode=thin \
          --name="sddc20.corp.internal" \
          --prop:vami.hostname="sddc20.corp.internal" \
          --prop:vami.ip0.SDDC-Manager="192.168.50.20" \
          --prop:vami.netmask0.SDDC-Manager="255.255.255.0" \
          --prop:vami.gateway.SDDC-Manager="192.168.50.254" \
          --prop:vami.domain.SDDC-Manager="corp.internal" \
          --prop:vami.searchpath.SDDC-Manager="corp.internal" \
          --prop:vami.DNS.SDDC-Manager="192.168.50.54" \
          --prop:ROOT_PASSWORD="VMware1!VMware1!" \
          --prop:LOCAL_USER_PASSWORD="VMware1!VMware1!" \
          --prop:guestinfo.ntp="192.168.50.54" \
          "VCF-SDDC-Manager-Appliance-9.0.1.0.24962180.ova" \
          "vi://root:VMware1!VMware1!@192.168.50.108/"
      args:
        executable: /bin/bash